### ISSUE TITLE
Add default support for OPTIONS which should return spec/doc for a given path.

### ISSUE THREAD

**Issue by jhthorsen** [jhthorsen/mojolicious-plugin-openapi#1]
https://github.com/jhthorsen/swagger2/pull/83

**Comment by kivilahtio** [comment]
The OPTIONS should be enabled by default and I see no point in disabling it.
It must be overloadable when specifying the exact OPTIONS-handler in the spec.
My implementation for the past Swagger2-plugin is here:
https://github.com/KohaSuomi/swagger2/blob/cors/lib/Mojolicious/Plugin/Swagger2.pm#L140

**Comment by jhthorsen** [comment]
I agree about enabling it by default.

**Comment by jhthorsen** [comment]
The implementation is marked as EXPERIMENTAL. Improvements and feedback are welcome.
