### ISSUE TITLE
Body parameters in HTML output

### ISSUE THREAD

**Issue by plk** [jhthorsen/mojolicious-plugin-openapi#10]
Consider the spec below. Since there can only be one body parameter definition, multiple body parameters have to be specifiec with a reference. However, when rendered with the automatic documentation URL (which is great, by the way), it does not resolve the reference and user is told in teh doc for the operation that there is a parameter called "AuthGenerate" which is not required. The actual params are spelled out correctly in the "Body" section for the operation but it is quite confusing for users to see a paramater called "AuthGenerate" which is not something they should really even see as it's just a name used internally to the spec to group body params. Perhaps these reference can be parsed out for the "Parameters" section so that the actual params and ther required status are visible, just like normal query params etc.?

```
swagger: '2.0'
info:
  title: REST API
  version: "1.0.0"
schemes:
  - https
basePath: /pcapiv1
produces:
  - application/json
paths:
  /auth:
    post:
      x-mojo-to: "auth#generate"
      summary: Generate JWT for username/password combination
      parameters:
        - name: AuthGenerate
          in: body
          description: username/password to be encoded as a JWT
          schema:
            $ref: '#/definitions/AuthGenerate'
      responses:
        default:
          description: Generic response object
          schema:
            $ref: '#/definitions/Response'
definitions:
  AuthGenerate:
    required:
      - username
      - password
      - domain
      - repository
    properties:
      username:
        description: username
        type: string
      password:
        description: password
        type: string
      domain:
        description: domain
        type: string
      repository:
        description: repository
        type: string
      securitydomain:
        description: Security Domain
        type: string
  Response:
    type: object
    description: JSON object with 'status' parameter and error array
    required:
      - status
      - errors
    properties:
      status:
        description: True/False status
        type: boolean
      errors:
        description: Array of any errors
        type: array
        items:
          type: string
      output:
        description: Array of any output
        type: array
        items:
          type: string

```

**Comment by jhthorsen** [comment]
Sorry. I don't understand what you're saying. I don't see any references when I render my documentation. Have a look at http://chat.thorsen.pm/api.html#op-post-user and https://github.com/Nordaaker/convos/blob/master/public/convos-api.json#L413

**Comment by plk** [comment]
Apologies, you are quite right, this is just a mistake on my part.

**Comment by jhthorsen** [comment]
Cool! I would like to make it more readable though... I'm hoping @leejo will do some magical thing, but I I'm not sure.

I think it's hard to make the documentation readable, and not missing information at the same time.

**Comment by plk** [comment]
It would be quite a plus to make it look really nice - this is a great thing for enterprise customers as automatic current documentation is a big selling point.
