### ISSUE TITLE
As a developer, I would like a tutorial for OpenAPI v3

### ISSUE THREAD

**Issue by jhthorsen** [jhthorsen/mojolicious-plugin-openapi#112]
https://github.com/jhthorsen/mojolicious-plugin-openapi/blob/master/lib/Mojolicious/Plugin/OpenAPI/Guides/Tutorial.pod is currently only for OpenAPI 2. "Someone" should write a guide for v3 as well.

When that is done, then Tutorial.pod should also be renamed.

The new tutorial for v3 should probably have a list of what is missing or not very well tested.

**Comment by HEM42** [comment]
I would like to help, quickly looking at it, do you want a separate Tutorial for v3 ?

I was thinking of "translating" the existing examples into v3 and remove the parts with doesn't apply to v3

As for missing/not very well tested list, I dont have any thing just yet for that part.

**Comment by jhthorsen** [comment]
I'm going to merge #142 at some point, so I'm closing this.

Thanks @HEM42!
