### ISSUE TITLE
Spec's with boolean as types die. Conflict with CPAN boolean dists boolean::TO_JSON ?

### ISSUE THREAD

**Issue by muenalan** [jhthorsen/mojolicious-plugin-openapi#12]
Info: The boolean CPAN module is required for MongoDB.

I am new to Mojo JSON handling, but it seems there is a conflict once the CPAN 'boolean' module is installed. I could track the issue quite far, but don't understand how to patch this.

The CPAN boolean distribution has:

    sub TO_JSON {
      Carp::croak "Need ref for this" unless ref $_[0];         # Added by myself for debugging
      ${$_[0]} ? \1 : \0
   }

and expects this method not to be called with arguments, or as a constructor (which OpenAPI.pm obviously does). This causes wrong initialization with the construct JSON/Validator.pm '0.86' line 301:

      $data = $data->TO_JSON if UNIVERSAL::can($data, 'TO_JSON');

as ends into 

   'boolean'->TO_JSON
  {
   return ${ 'boolean' };
  }

which die's because the string 'boolean' is not a ref. 

QUESTION: Could someone fix this ?

INFO: My swagger2 json has under definitions 'boolean' as a type for 'complete'. 

       "Order": {
            "type": "object",
            "properties": {
                "id": {
                    "type": "integer",
                    "format": "int64"
                },
                "Id": {
                    "type": "integer",
                    "format": "int64"
                },
                "quantity": {
                    "type": "integer",
                    "format": "int32"
                },
                "shipDate": {
                    "type": "string",
                    "format": "date-time"
                },
                "status": {
                    "type": "string",
                    "description": "Order Status"
                },
                "complete": {
                    "type": "boolean"
                }
            }

Once I try to load it, it die's with this stack trace:

ERROR* parse_line: Need ref for this at /usr/local/share/perl/5.18.2/boolean.pm line 83.
	boolean::TO_JSON("boolean") called at /usr/local/share/perl/5.18.2/JSON/Validator.pm line 301
	JSON::Validator::_validate(JSON::Validator=HASH(0xea5d588), "boolean", "/definitions/Order/properties/complete/type", HASH(0xea2ead0)) called at /usr/local/share/perl/5.18.2/JSON/Validator.pm line 599
	JSON::Validator::_validate_type_object(JSON::Validator=HASH(0xea5d588), HASH(0xeb59670), "/definitions/Order/properties/complete", HASH(0xea2e218)) called at /usr/local/share/perl/5.18.2/JSON/Validator.pm line 310
	JSON::Validator::_validate(JSON::Validator=HASH(0xea5d588), HASH(0xeb59670), "/definitions/Order/properties/complete", HASH(0xea2e218)) called at /usr/local/share/perl/5.18.2/JSON/Validator.pm line 599
	JSON::Validator::_validate_type_object(JSON::Validator=HASH(0xea5d588), HASH(0xeb93a18), "/definitions/Order/properties", HASH(0xea2e6f8)) called at /usr/local/share/perl/5.18.2/JSON/Validator.pm line 310
	JSON::Validator::_validate(JSON::Validator=HASH(0xea5d588), HASH(0xeb93a18), "/definitions/Order/properties", HASH(0xea2e6f8)) called at /usr/local/share/perl/5.18.2/JSON/Validator.pm line 599
	JSON::Validator::_validate_type_object(JSON::Validator=HASH(0xea5d588), HASH(0xec6eda0), "/definitions/Order", HASH(0xea364e0)) called at /usr/local/share/perl/5.18.2/JSON/Validator.pm line 310
	JSON::Validator::_validate(JSON::Validator=HASH(0xea5d588), HASH(0xec6eda0), "/definitions/Order", HASH(0xea364e0)) called at /usr/local/share/perl/5.18.2/JSON/Validator.pm line 599
	JSON::Validator::_validate_type_object(JSON::Validator=HASH(0xea5d588), HASH(0xec6eb30), "/definitions", HASH(0xea36468)) called at /usr/local/share/perl/5.18.2/JSON/Validator.pm line 310
	JSON::Validator::_validate(JSON::Validator=HASH(0xea5d588), HASH(0xec6eb30), "/definitions", HASH(0xea36468)) called at /usr/local/share/perl/5.18.2/JSON/Validator.pm line 599
	JSON::Validator::_validate_type_object(JSON::Validator=HASH(0xea5d588), HASH(0xe99cd00), "", HASH(0xea5d7c8)) called at /usr/local/share/perl/5.18.2/JSON/Validator.pm line 310
	JSON::Validator::_validate(JSON::Validator=HASH(0xea5d588), HASH(0xe99cd00), "", HASH(0xea5d7c8)) called at /usr/local/share/perl/5.18.2/JSON/Validator.pm line 89
	JSON::Validator::validate(JSON::Validator=HASH(0xea5d588), HASH(0xe99cd00)) called at /usr/local/share/perl/5.18.2/Mojolicious/Plugin/OpenAPI.pm line 130
	Mojolicious::Plugin::OpenAPI::_load_spec(Mojolicious::Plugin::OpenAPI=HASH(0xea5d528), CellApp=HASH(0xeafb288), HASH(0xea74260)) called at /usr/local/share/perl/5.18.2/Mojolicious/Plugin/OpenAPI.pm line 21
	Mojolicious::Plugin::OpenAPI::register(Mojolicious::Plugin::OpenAPI=HASH(0xea5d528), CellApp=HASH(0xeafb288), HASH(0xea74260)) called at /usr/local/share/perl/5.18.2/Mojolicious/Plugins.pm line 46
	Mojolicious::Plugins::register_plugin(Mojolicious::Plugins=HASH(0xeb09f48), "OpenAPI", CellApp=HASH(0xeafb288), HASH(0xea74260)) called at /usr/local/share/perl/5.18.2/Mojolicious.pm line 175
	Mojolicious::plugin(CellApp=HASH(0xeafb288), "OpenAPI", HASH(0xea74260)) called at mojo/cell_app/lib/CellApp.pm line 96

**Comment by jhthorsen** [comment]
I don't think it will be fixed. The "standard" boolean used by several perl JSON encoders (such as Mojo::JSON) is https://metacpan.org/pod/JSON::PP#JSON::PP::true and `JSON::PP::false`.

My solution in these cases are to traverse the data and replace any occurrences of boolean (objects) and replace them with `JSON::PP::true` and `JSON::PP::false`.

**Comment by muenalan** [comment]
Sorry for the stress, but I cannot find a 'boolean' package in JSON::PP.pm:

$ perl -MJSON::PP -MData::Dump=pp -e 'print pp( 'boolean'->TO_JSON )'
Can't locate object method "TO_JSON" via package "boolean" (perhaps you forgot to load "boolean"?) at -e line 1.

But, grep in /usr/local/share/perl says its most likely hitting:

JSON.pm:                *UNIVERSAL::TO_JSON = sub ..

But that does not get called either with your code. Also with Mojo::JSON, there is never a 'boolean' package.

$ perl -MMojo::JSON -MData::Dump=pp -e 'print pp( 'boolean'->TO_JSON )
Can't locate object method "TO_JSON" via package "boolean" (perhaps you forgot to load "boolean"?) at -e line 1.

I figured, the code might 

  $data = $data->TO_JSON if UNIVERSAL::can($data, 'TO_JSON');

is not called usually ? Only, once the 'boolean' module is loaded, but then it should be called boolean::TO_JSON() ?

PS: As MongoDB might be not very uncommon in web projects, i guess its worth the effort to trace this down.

**Comment by muenalan** [comment]
SOLVED: Indeed if I comment the line in JSON::Validator out

# $data = $data->TO_JSON if UNIVERSAL::can($data, 'TO_JSON');

everything runs fine. Would I have to expect any side-effects ?

**Comment by jhthorsen** [comment]
Hey. Sorry for being so slow! I just fixed this in JSON::Validator. The next version should be available on CPAN in a couple of hours. Upgrade to JSON::Validator to version 0.87 and you'll be fine.

Thanks for the bug report and all the help 👍

**Comment by jhthorsen** [comment]
BTW: You might want to reconsider using MongoDB. If you're not invested too deep or if you don't have people really knowing how to set ip up, you might be in deep water.

Just a friendly advice. I don't want to start a discussion.
