### ISSUE TITLE
"coerce(1) will be deprecated"

### ISSUE THREAD

**Issue by ViktorNacht** [jhthorsen/mojolicious-plugin-openapi#130]
FYI, getting the following warning:

coerce(1) will be deprecated. at /opt/perl5/perls/puravida/lib/site_perl/5.24.3/Mojolicious/Plugin/OpenAPI.pm line 29.

Not sure if it matters, but I'm using this module via Yancy.

**Comment by christopherraa** [comment]
@ViktorNacht The warning you are seeing is also covered in this issue: https://github.com/jhthorsen/openapi-client/issues/17

There you can see links to where in the code the warning originates.

**Comment by ViktorNacht** [comment]
Ugh, thank you very much. Sorry to clutter the issues.
