### ISSUE TITLE
should $c->param('param_name') warn / bail if not spec compliant ?

### ISSUE THREAD

**Issue by rmallah** [jhthorsen/mojolicious-plugin-openapi#155]
once we load the openapi spec via plugin , it will be nice
if $c->param('some_param') in controller code raises an alarm if
the 'some_param' is not mentioned in the specs.

**Comment by jhthorsen** [comment]
This is too much work, and the gain is very little from my perspective. Also, what would happen if you do `$c->req->url->query->param()` instead? I don't see this being doable.

I encourage you to write more unit tests instead. You can't control your user input, but you can control the path of your program.

**Comment by jhthorsen** [comment]
I'm keeping it open for a bit though, in case new information/reasons arise.

**Comment by rmallah** [comment]
Thanks for the response, i am posting from the perspective of someone converting existing
unorganized APIs to openAPI format. I am loving it(openAPI & this plugin) and trying to 
post observations.

**Comment by jhthorsen** [comment]
Thanks for the input! Appreciate it :)
