### ISSUE TITLE
Support for v3 object parameters

### ISSUE THREAD

**Issue by SebMourlhou** [jhthorsen/mojolicious-plugin-openapi#159]
Parameters of type object are supported in OpenAPI 3.
https://swagger.io/docs/specification/serialization/

It would be nice if the plugin could support this.

**Comment by jhthorsen** [comment]
What's missing here? https://github.com/jhthorsen/mojolicious-plugin-openapi/pull/154

**Comment by SebMourlhou** [comment]
#154 allowed the plugin to support the parameters of type "array".
This ticket is about the parameters of type "object" (hash) which are supported in OpenAPI 3 (not in v2). 

I'd like to make a PR for this.
Already began but not enough tested... If I had enough time, I'll make a proposal next week.

Thanks for this great plugin !

**Comment by SebMourlhou** [comment]
Have you seen my comment ?

**Comment by jhthorsen** [comment]
I did see you comment, but then I lost track of time.

Closed by #184.
