### ISSUE TITLE
Errors testing 2.22 "... could not be found in __DATA__ section of . ..."

### ISSUE THREAD

**Issue by rkleemann** [jhthorsen/mojolicious-plugin-openapi#163]
Attempting to install the latest version gets a lot of test failures, on all versions of Perl.  I've attached my build.log.

[build.log](https://github.com/jhthorsen/mojolicious-plugin-openapi/files/4278154/build.log)

Note, that the error messages appear similar to https://github.com/mojolicious/json-validator/issues/193

**Comment by jhthorsen** [comment]
Pretty sure this was because M::P::OpenAPI depended on an old version of J::V. You can fix it yourself by installing JSON::Validator first.

Will be fixed in 2.23.
