### ISSUE TITLE
Support defaults in requestBody properties

### ISSUE THREAD

**Issue by mschout** [jhthorsen/mojolicious-plugin-openapi#176]
In `requestBody`, it is possible to specify a `default` for each property per OpenAPI 3.0 like this:

```
requestBody:
  required: true
  content:
    application/json:
      schema:
        type: object
        properties:
          foo:
            type: string
            default: bar
```

See https://github.com/OAI/OpenAPI-Specification/blob/master/schemas/v3.0/schema.yaml#L311 for where this is in the spec.

Currently this is not handled by the plugin, fix coming in PR shortly.

**Comment by jhthorsen** [comment]
I don't want this code in mojolicious-plugin-openapi, since it involves looping through the body twice, making validation twice as slow. Please help fixing jhthorsen/json-validator#155 instead.

**Comment by mschout** [comment]
Sure, I'll look there. thanks!
