### ISSUE TITLE
Double resolve of specification

### ISSUE THREAD

**Issue by mrenvoize** [jhthorsen/mojolicious-plugin-openapi#19]
We're resolving the specification twice during register.

```perl
sub register {
  my ($self, $app, $config) = @_;
  my $api_spec = $self->_load_spec($app, $config);                             # <-- First resolve

  unless ($app->defaults->{'openapi.base_paths'}) {
    $app->helper('openapi.validate'    => \&_validate);
    $app->helper('openapi.valid_input' => sub { _validate($_[0]) ? undef : $_[0] });
    $app->helper('openapi.spec'        => \&_helper_spec);
    $app->helper('reply.openapi'       => \&_reply);
    $app->hook(before_render => \&_before_render);
    $app->renderer->add_handler(openapi => \&_render);
    push @{$app->renderer->classes}, __PACKAGE__;
  }

  $self->{log_level} = $ENV{MOJO_OPENAPI_LOG_LEVEL} || $config->{log_level} || 'warn';
  $self->{renderer} = $config->{renderer} || \&_render_json;
  $self->_validator->schema($api_spec->data)->coerce($config->{coerce} // 1);  # <-- Second Resolve
  $self->_add_routes($app, $api_spec, $config);
}
```

Initially, I thought this was just a bit inefficient, but it also seems to lead to a deeper problem inside JSON::Validator whereby the register call never completes.  I've tracked it down to an infinite recursion of the while loop in _resolve_schema.

I'm struggling to write a test for either.. my initial attempts are in the currently failing recursion branch.

**Comment by jhthorsen** [comment]
I agree that we should remove the line where we set schema($api_spec). I wanted to link to the line, but I found there's more things that should be changed when we do that...

**Comment by mrenvoize** [comment]
Just for clarification to anyone else stumbling across this one.  We fixed the recursion issue in https://github.com/jhthorsen/json-validator/commit/f17287ee0063ddc5d9594804fecde2d05f24fc13 which makes this a bit less urgent.. But it would still be nice to clean up the double resolve here too ;)

**Comment by jhthorsen** [comment]
Is this fixed in b535381089b407418d304712dc1f8d9474ac015b?

**Comment by jhthorsen** [comment]
Pretty sure this is already fixed. Please let me know if it's not @mrenvoize.

**Comment by mrenvoize** [comment]
@jhthorsen I think the symptom that exposed this issue to me has been fixed (in that we solved the recursion issue), but I think we are still double resolving the spec.. it's more of a 'clarifying the intent of the code' thing than an actual bug now.

**Comment by jhthorsen** [comment]
I see now that it's not fixed. I thought it was fixed in https://github.com/jhthorsen/mojolicious-plugin-openapi/commit/b535381089b407418d304712dc1f8d9474ac015b, but the spec is still written back at https://github.com/jhthorsen/mojolicious-plugin-openapi/blob/1790e40332aae052270b6df3b45e73c181584634/lib/Mojolicious/Plugin/OpenAPI.pm#L44

**Comment by mrenvoize** [comment]
Yup, just set MOJO_OPENAPI_DEBUG=1 and this pops up in my logs at app startup:

```
[JSON::Validator] Loading schema /home/rebus/rebus-list/specification/index.json namespace=/home/rebus/rebus-list/specification/index.json scheme=file
[JSON::Validator] Register id=/home/rebus/rebus-list/specification/index.json namespace=/home/rebus/rebus-list/specification/index.json
[JSON::Validator] Resolving schema /home/rebus/rebus-list/specification/index.json
[JSON::Validator] Loading schema /home/rebus/rebus-list/specification/index.json namespace=/home/rebus/rebus-list/specification/index.json scheme=file
[JSON::Validator] Register id=/home/rebus/rebus-list/specification/index.json namespace=/home/rebus/rebus-list/specification/index.json
[JSON::Validator] Resolving schema /home/rebus/rebus-list/specification/index.json
```

**Comment by mrenvoize** [comment]
ooh.. you commented at the same time as me.. fun.

I 'looks' like a trivial enough fix but I wanted to test it a bot mroe thoroughly before I submitted a pull request..  for me at least, just removing the `->schema($api_spec->data)` part of that line removed the superflous resolve and didn't appear to have any knock on effects.

**Comment by jhthorsen** [comment]
Yeah! I think even the code is cleaner to read now 👍
