### ISSUE TITLE
Enhancement: Support for 'OpenAPI Specification version 3.0'

### ISSUE THREAD

**Issue by mrenvoize** [jhthorsen/mojolicious-plugin-openapi#20]
This is still in technical draft at the time of writing, with a 'first Implementor Draft' due for release on February 28th 2017.

https://www.openapis.org/blog/2017/01/24/a-new-year-a-new-specification give's a broad overview.

Corresponding issue for JSON::Validator  https://github.com/jhthorsen/json-validator/issues/41

**Comment by elcamlost** [comment]
https://github.com/OAI/OpenAPI-Specification/releases 
It's now in RC state.
Do you have any plans to support it in near future?
What do you think, it should be new module or existing?
Do you need any help?

**Comment by jhthorsen** [comment]
@elcamlost: Can't do anything without a schema.

**Comment by jhthorsen** [comment]
Please re-open when we have a spec. I'll keep https://github.com/jhthorsen/json-validator/issues/41 open.
