### ISSUE TITLE
Strict input checking?

### ISSUE THREAD

**Issue by augensalat** [jhthorsen/mojolicious-plugin-openapi#207]
(By default?) this plugin does permissive validation: Any fields that are not specified in the OpenAPI spec are ignored.

Is it possible to switch validation to be "strict" instead?

Otherwise this would be my feature request.

**Comment by jhthorsen** [comment]
Can you please provide a real world usecase?

The input parameters are tracked, so it’s doable. https://github.com/jhthorsen/mojolicious-plugin-openapi/blob/c9408c833e5822b2538430fbdc804c3c795ea4eb/lib/Mojolicious/Plugin/OpenAPI/Parameters.pm#L35

**Comment by augensalat** [comment]
> While this could be a feature that the plugin could support, I think in the end you'd want this to be in your spec file. For something like a schema it is easy with `additionalProperties: false` [...]

@jberger, that was exactly the option I was missing. Tested, works, problem solved. Thank you very much!
