### ISSUE TITLE
Integer and Number type query parameters treated as String types in OASv2

### ISSUE THREAD

**Issue by lafokamotion** [jhthorsen/mojolicious-plugin-openapi#216]
Working with OpenAPI v2, given the following definition of a parameter:
![image](https://user-images.githubusercontent.com/12587263/118271455-496aef80-b48f-11eb-9fe1-d1ff03e38b40.png)

I then hit the route with the query parameter defined as `count=5` and receive the following OpenAPI generated response:
![image](https://user-images.githubusercontent.com/12587263/118271721-a797d280-b48f-11eb-8688-3ebf0783f29c.png)

I can skip adding the query param, in which case, the default value of 300 is properly used for the count param value and no failure occurs.

This issue also occurs with number type parameters. I did manage to convert my spec to OpenAPI v3 and it appears to not be an issue for v3.

This seems to be an issue starting at version 4.00

**Comment by jhthorsen** [comment]
I don't see how this is possible (see the tests in e129529) unless you have disabled coercion.
