### ISSUE TITLE
Warnings after update to latest release

### ISSUE THREAD

**Issue by ure** [jhthorsen/mojolicious-plugin-openapi#224]
Hi there,

After we did an update to the latest release (coming from the previous release)
we get these
Use of uninitialized value in string eq at /app/local/lib/perl5/Mojolicious/Plugin/OpenAPI/Parameters.pm line 131.
I'll take a look in the code lateron

**Comment by jhthorsen** [comment]
ref will never return "undef", so the issue was how schema_type() was used. Will be part of the next release.
