### ISSUE TITLE
Just a quick copy from IRC

### ISSUE THREAD

**Issue by Skeeve** [jhthorsen/mojolicious-plugin-openapi#232]
08:30 (Skeeve) Hi batman. Maybe it's a known issue and I need not investigat further. I'm using OpenAPI v3 and have a path parameter which is a base64 encoded token like /api/v1/user/1yCPLtcgjzyawhHslfbz33_UJLfX
08:31 (Skeeve) That seems to work as long as there is no dot in the token, in which case I get a 404
08:32 (Skeeve) Like with this: /api/v1/user/XRh.xl0Yf9KawxHskRDQZu6lvUhd
08:41 (Skeeve) Oh wait. There must be something in my part wrong "." is no base 64 character :(
08:52 (Skeeve) Okay… It seems there is an issue with "." To clarify: My base64 encoded string is tr-ed to translate "=", "+" and "/" into "-", "_", and ".". When the "." occours, Openapi fails to find my path. I replaced "." now with "!" and that works.

Sorry for not having more information a.t.m.

**Comment by jhthorsen** [comment]
As mentioned on IRC: https://metacpan.org/dist/Mojolicious-Plugin-OpenAPI/view/lib/Mojolicious/Plugin/OpenAPI/Guides/OpenAPIv2.pod
