### ISSUE TITLE
[Mojolicious::Plugin::OpenAPI::Security] should use http status code 403

### ISSUE THREAD

**Issue by abraxxa** [jhthorsen/mojolicious-plugin-openapi#247]
Mojolicious::Plugin::OpenAPI::Security should use http status code 403, not 401, when the user is authenticated but the authorization check fails.
See https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/403 for a good definition of the status codes.

I'd need it be let the frontend know the difference between unauthenticated (-> redirect to login page) and displaying an unauthorized error message but staying on the current page.

Thanks!

**Comment by abraxxa** [comment]
I found a workaround using `$c->stash(status => 403);` which isn't documented though.

**Comment by jhthorsen** [comment]
It's documented in Mojolicious::Controller.
