### ISSUE TITLE
empty responses should default to http status code 204

### ISSUE THREAD

**Issue by abraxxa** [jhthorsen/mojolicious-plugin-openapi#249]
`$self->render(openapi => {});` should make status default to 204 instead of 200.

**Comment by jhthorsen** [comment]
That doesn't make any sense. Why would an empty object be an empty response? You can just do render(text => '', status => 204) if you like.

**Comment by abraxxa** [comment]
I know that I can work around it but it would be nice if the module adheres to the http standard by default.
For example DELETE requests don‘t return anything but still respond with code 200.

**Comment by jhthorsen** [comment]
My point is that enforcing a default status code doesn't make any sense, when different people might want that to be 200, 201, 204, ... I would also consider it a breaking change. Third: It's very easy to set the status code from the controller. Much easier than maintaining if/else/lookups to do the same thing.
