### ISSUE TITLE
Incorrect disambiguation of path by pattern

### ISSUE THREAD

**Issue by jjatria** [jhthorsen/mojolicious-plugin-openapi#26]
I have a spec that defines ambiguous paths like `/user/list` and `/user/{id}`. Based on some minimal tests I've run, this _should_ not be a problem. And using plain Mojolicious, as long as the more specific path comes first, this definitely works. But I've bumped into at least one case in which this does not happen correctly. 

I've tried to put together the smallest demo application demonstrating this problem, which is hosted in [its own repository](https://gitlab.com/jjatria/openapi-path-test). It can be executed with `morbo bin/server` and tested with `mojo get localhost:3000/decode`, which should print `{"target":"decode"}` (but doesn't).

The problematic part of [the API spec](https://gitlab.com/jjatria/openapi-path-test/blob/6cd091b2c3e6bf00761bc3825f903e5b4a20b249/api.yaml) is this:

```
paths:
  /decode:
    get:
      operationId: "decode"
      x-mojo-to: "controller#decode"
      parameters: []
      responses:
        200:
          description: Success

  /{id}:
    get:
      operationId: "id"
      x-mojo-to: "controller#id"
      parameters:
        - name: id
          in: query
          required: true
          type: string
      responses:
        200:
          description: Success
```

I'm still trying to figure out where the problem is, but I'd really like to be able to have this plugin disambiguate these paths. Or am I doing something wrong?

**Comment by jhthorsen** [comment]
Sorry for the late response. Going to make a new release later tonight.

Thanks for reporting in 👍
