### ISSUE TITLE
Deprecation of Mojo::Util::slurp

### ISSUE THREAD

**Issue by plk** [jhthorsen/mojolicious-plugin-openapi#30]
I don't have permissions to re-open #23 so opening a new one - I am still getting this message with 1.09 and Mojolicious 7.26.

**Comment by jhthorsen** [comment]
Can't you comment on the issue..?

**Comment by jhthorsen** [comment]
Which line does it complain about?

**Comment by plk** [comment]
I did comment a couple of weeks ago and assumed it wasn't being looked at any more because it was closed ...

`Mojo::Util::slurp is DEPRECATED in favor of Mojo::File::slurp at /usr/local/informatica/perl/lib/site_perl/5.24.0/Mojolicious/Plugin/OpenAPI.pm line 140.`

**Comment by leejo** [comment]
This will push the min required version of Mojolicious to 7.15: https://github.com/kraih/mojo/blob/master/Changes#L56

**Comment by jhthorsen** [comment]
@plk: which version of JSON::Validator do you have?

**Comment by plk** [comment]
0.90

**Comment by marcusramberg** [comment]
@jhthorsen++

**Comment by plk** [comment]
Ahah, ok, I didn't notice the change in `JSON::Validator` because it wasn't picked up as a dependency ... upgrading that seems to get rid of the error.

**Comment by jhthorsen** [comment]
Cool! Sorry for not bumping the version earlier :/
