### ISSUE TITLE
 Ability to change the format of the "Default error document"

### ISSUE THREAD

**Issue by le-garff-yoann** [jhthorsen/mojolicious-plugin-openapi#34]
Is it currently possible?

**Comment by jhthorsen** [comment]
I have some questions to you:

1. Why do you want to do that?
2. Do you mean the error document after validating or on an internal server error?

What you do for the error document for validating is that you do the whole validation by your self and the render an error if there are any errors: https://metacpan.org/pod/Mojolicious::Plugin::OpenAPI#openapi.validate

For internal server errors, you can install a "before_render" hook before M::P::OpenAPI and then unset "exception" (I think) https://metacpan.org/source/JHTHORSEN/Mojolicious-Plugin-OpenAPI-1.13/lib/Mojolicious/Plugin/OpenAPI.pm#L119

**Comment by le-garff-yoann** [comment]
I use a specific response object for "errors" and i wish to use it in place of the default object for "validation", "internal servor error" and "not implemeted".

The documentation led me believe that it's possible to override the `openapi.not_implemented` helper to do the last one but i wasn't sure of the possibility of doing the exact same thing for `openapi.valid_input` (or `validate`, i'm not sure!) and "internal server error" (i will try to solve this one with the `before_render` hook).

 Thank you.

**Comment by jhthorsen** [comment]
Would very much like to know what you find out and if what I suggest works for you.

I might also take a PR if you think this feature should be part of the core package.

**Comment by jhthorsen** [comment]
I did understand that you have a specific response you want to use. What I asked about was *why* do you need a different response.

**Comment by le-garff-yoann** [comment]
I wish to have a similar "error object interface" for the whole scope of the API.

**Comment by jhthorsen** [comment]
And why can't you use the default? What is the structure you want?

**Comment by le-garff-yoann** [comment]
A structure of this shape:
```javascript
{
  "messages": [ // want to put plugin errors here !
    { "severity": "warning", "text": "...." },
    { "severity": "ok", "text": "...." }
  ]
}
```
Concerning the PR, i was thinking of a proposal along theses lines: https://gist.github.com/le-garff-yoann/780d9c7588993d4e9d6115d76907abd8/revisions

**Comment by jhthorsen** [comment]
Please have a look at #35 to see if that code can work for you.

I don't know how to fix rendering of "404" responses though.

**Comment by le-garff-yoann** [comment]
What was used with the "not_implemented" helpler before #35 could also be functional for 404 error handling.

**Comment by le-garff-yoann** [comment]
> Please have a look at #35 to see if that code can work for you.

Yes, it works. ;)

**Comment by jhthorsen** [comment]
Using the same solution as "not_implemented" is not consistent. Please comment on #35, if you have more input.

**Comment by jhthorsen** [comment]
It's now available on CPAN. Enjoy!

https://metacpan.org/release/JHTHORSEN/Mojolicious-Plugin-OpenAPI-1.15

**Comment by le-garff-yoann** [comment]
Thanks!
