### ISSUE TITLE
bundling split specs

### ISSUE THREAD

**Issue by mrenvoize** [jhthorsen/mojolicious-plugin-openapi#39]
I would love to see a parallel to the 'bundle' command explained here: https://github.com/BigstickCarpet/swagger-parser/blob/master/docs/swagger-parser.md#bundleapi-options-callback (code at: https://github.com/BigstickCarpet/json-schema-ref-parser/blob/master/lib/bundle.js)

This would allow us to remove our dependency on Data::Dumper for a 'crude' but recursive loop resistant serialisation of the specification for outputting to HTML documentation (and should also serve to fix the .json rendering for the whole spec which currently goes into an endless loop (or rather just 500's when we hit max depth in your chosen JSON module) for recursive schema's.

I intend to look at this.. hopefully getting my head around the javascript implementation with the aim of porting similar into JSON::Validator.. this is more a marker of my intention.

**Comment by jhthorsen** [comment]
Is this fixed by https://github.com/jhthorsen/mojolicious-plugin-openapi/commit/6147c0d53e30fb700dd33bf59c62076c04773612#diff-cfc5fb41e145df4fa1713dbc13ec3df6R267 ?
