### ISSUE TITLE
Implement ability to keep documentation near a subroutine

### ISSUE THREAD

**Issue by KES777** [jhthorsen/mojolicious-plugin-openapi#41]
I document my modules like this:

![documentation](http://joxi.net/l2ZMDx6I8z5VPm.jpg)

I can convert that to OpenAPI and put into `swagger.json` file. But ability to keep that doc near subroutine will be more handy.

I think this maybe done with help of [JSON::Validator](https://metacpan.org/pod/JSON::Validator#SYNOPSIS). But I do not found Doc

**Comment by jhthorsen** [comment]
I don't understand what you want.

Do you want to convert POD into API spec? I won't do that, and it won't be part of the core of M::P::OpenAPI, nor JSON::Validator.

Do you want to convert the spec into POD? I tried to do that, but I've abandoned the idea, since I have no use for it myself. You can see my (flawed) implementation here: https://github.com/jhthorsen/swagger2/blob/master/lib/Swagger2/POD.pm

Please let me know if there's something else you want.

**Comment by KES777** [comment]
I suppose next code:

```
use JSON::Validator qw/ extend_schema /;

extend_schema {
  /login:    
    post:
      subroutine: check               <<<<<<<<<<<<<<<<<<<< the key
      description: Perfroms user authentication
      produces:
        - application/json
      parameters:
        - name: contact
          description: User's email or phone
          in: body
          type: string
          schema:
            type: string
        - name: password
          description: User's password
          in: body
          schema:
            type: string
      responses:
        '200':
          description: Everything is OK
};

sub check {
     ....
     here is sub I want to describe
}

1;
```

After this module loading is finished. The schema definition will be extended by this one

**Comment by KES777** [comment]
I just want to write instead of POD the OpenAPI spec. 
and this spec I want to put at same place where POD was.

**Comment by jhthorsen** [comment]
I won't do this. The plugin is built on the idea that you have a specification in yaml/json that is sharable between developers that has no idea about Perl/POD/whatever.

You're welcome to open a PR to either JSON::Validator or this plugin though. If it's short enough, then I might consider it, but either way I might make enough changes so you can create a different distribution that integrates with one of the modules.
