### ISSUE TITLE
ReDoc for api documentation rendering

### ISSUE THREAD

**Issue by elcamlost** [jhthorsen/mojolicious-plugin-openapi#45]
https://github.com/Rebilly/ReDoc

ReDoc is a cool tool for generating openapi documentation based only on schema fille. I think, i can create a PR to use it for html documentation renderer.

What do you think about it? Is it usefull feature? If you agree, I can implement this feature.

**Comment by jhthorsen** [comment]
I would like to replace the current renderer with something else, and ReDoc looks promising.

One of the features I need is to be able to press "print" and allow the whole specification to be saved as a readable pdf.

Looks like ReDoc is pretty close. I'll put this issue up to a vote, while I will look at ReDoc more closely myself.

**Comment by jhthorsen** [comment]
I've looked into ReDoc, and it simply doesn't look good enough on print.
