### ISSUE TITLE
 OpenAPI plugin error from "spec/event.yml#/paths/~1event~1update" 

### ISSUE THREAD

**Issue by nancyyaweili** [jhthorsen/mojolicious-plugin-openapi#48]
Hi, 

We've been using the OpenAPI for quite a while and everything seems to be working really well in our environment. 

However, just in the recently couple weeks, when starting server in development environment, I'm getting error complaining 

``` Can't load application from file "/work/script/app.pl": Can't use string ("spec/event.yml#/paths/~1event~1u"...) as a HASH ref while "strict refs" in use at /home/build/.plenv/versions/5.24.0/lib/perl5/site_perl/5.24.0/Mojolicious/Plugin/OpenAPI.pm line 102.```

My OpenAPI version is 1.21, mojo version is 7.39.  Please refer to the bottom about the spec content.  

While debugging the program,  line 102 of OpenAPI.pm was giving the trouble:
` my $name    = $op_spec->{'x-mojo-name'} || $op_spec->{operationId};`
$op_spec turns out to be a string and has the content of `spec/event.yml#/paths/~1event~1update`.

If I replace path ref with normal content, the program will run well. However, we've been using the same spec for quite a long time and it is only recently that it failed to load. I am not sure whether there are any change for the code base or the dependent modules. 

It is highly appreciated if you could have any pointers or suggestions. 

Regards,
Nancy

file spec.yml:
```
swagger: '2.0'

info:
  title: YBI Distribution API
  description: Service to handle all functions relating to distributing listings to 3rd parties
  version: "1.3.6"

schemes:
  - https
host: xxx
basePath: /xxx/v1
produces:
  - application/json
consumes:
  - application/json
paths:
      /event/update:
    $ref: spec/event.yml#/paths/~1event~1update
```

file spec/event.yml
```
paths:
  /event/update:
    post:
      summary: Trigger an update to 1 or more properties
      description: Notify the API of an update that needs processing.
      x-mojo-to:
        controller: Event
        action: Update
      parameters:
        - name: "events"
          in: "body"
          description: "Data structure of events to process"
          required: true
          schema:
            $ref: "#/definitions/events"
      responses:
        200:
          $ref: "#/responses/updateSuccess"
        default:
          $ref: '../spec.yml#/responses/http_status'
```

**Comment by nancyyaweili** [comment]
This issue is caused by [JSON::Validator version 1.05 ](https://github.com/jhthorsen/json-validator/issues/82). Once I reverted JSON::Validator to version 1.00, the problem goes away. 
Thanks.

**Comment by jhthorsen** [comment]
You can also load the plugin with `{allow_invalid_ref => 1}` as a temporary fix.

Hopefully I will get out a fix during the weekend, but I can't promise anything 😞

**Comment by nancyyaweili** [comment]
Thank you for the reply. All good.

**Comment by jhthorsen** [comment]
Can you see if it works better with the latest versions?

```
cpanm https://github.com/jhthorsen/json-validator/archive/master.tar.gz
cpanm https://github.com/jhthorsen/mojolicious-plugin-openapi/archive/master.tar.gz
```

These versions should also be available on CPAN soon.

**Comment by jhthorsen** [comment]
Pretty sure this is fixed. Please re-open if it's not
