### ISSUE TITLE
[error] Unsupported $in: . Please report at https://github.com/jhthorsen/json-validator at

### ISSUE THREAD

**Issue by sklukin** [jhthorsen/mojolicious-plugin-openapi#50]
Hi, Jan!

I have some route in spec
```
  '/question/answer':
    post:
      x-mojo-name: save_answer
      x-mojo-to: 'Admin::Questions#save_answer'
      parameters:
        - $ref: '#/parameters/question_id_post'
        - $ref: '#/parameters/event_id_post'
        - name: answer
          in: formData
          type: string
          required: true
      responses:
        200:
          description: Add answer to question
          schema:
            $ref: '#/definitions/success'
        202:
          description: Add or update customer and add to calendar
          schema:
            $ref: '#/definitions/error'
```

and when I send data to this route a have that errot

[Sun Nov 19 08:14:26 2017] [debug] Routing to controller "Pi::Controller::Admin::Questions" and action "save_answer"
Use of uninitialized value $in in string eq at /usr/local/share/perl/5.22.1/JSON/Validator/OpenAPI.pm line 49.
Use of uninitialized value $in in string eq at /usr/local/share/perl/5.22.1/JSON/Validator/OpenAPI.pm line 53.
Use of uninitialized value $in in string eq at /usr/local/share/perl/5.22.1/JSON/Validator/OpenAPI.pm line 58.
Use of uninitialized value $in in string eq at /usr/local/share/perl/5.22.1/JSON/Validator/OpenAPI/Mojolicious.pm line 7.
Use of uninitialized value $in in string eq at /usr/local/share/perl/5.22.1/JSON/Validator/OpenAPI/Mojolicious.pm line 10.
Use of uninitialized value $in in string eq at /usr/local/share/perl/5.22.1/JSON/Validator/OpenAPI/Mojolicious.pm line 13.
Use of uninitialized value $in in string eq at /usr/local/share/perl/5.22.1/JSON/Validator/OpenAPI/Mojolicious.pm line 16.
Use of uninitialized value $in in string eq at /usr/local/share/perl/5.22.1/JSON/Validator/OpenAPI/Mojolicious.pm line 20.
Use of uninitialized value $_[0] in concatenation (.) or string at /usr/local/share/perl/5.22.1/JSON/Validator/OpenAPI.pm line 294.
[Sun Nov 19 08:14:26 2017] [error] Unsupported $in: . Please report at https://github.com/jhthorsen/json-validator at /usr/local/share/perl/5.22.1/JSON/Validator/OpenAPI.pm line 294.
	JSON::Validator::OpenAPI::_confess_invalid_in(undef) called at /usr/local/share/perl/5.22.1/JSON/Validator/OpenAPI/Mojolicious.pm line 24
	JSON::Validator::OpenAPI::Mojolicious::_get_request_data(JSON::Validator::OpenAPI::Mojolicious=HASH(0x3bf7838), Pi::Controller::Admin::Questions=HASH(0x3eda788), undef) called at /usr/local/share/perl/5.22.1/JSON/Validator/OpenAPI.pm line 59
	JSON::Validator::OpenAPI::validate_request(JSON::Validator::OpenAPI::Mojolicious=HASH(0x3bf7838), Pi::Controller::Admin::Questions=HASH(0x3eda788), HASH(0x3e56bd0), HASH(0x3eebb10)) called at /usr/local/share/perl/5.22.1/Mojolicious/Plugin/OpenAPI.pm line 380
	Mojolicious::Plugin::OpenAPI::_validate(Pi::Controller::Admin::Questions=HASH(0x3eda788)) called at /usr/local/share/perl/5.22.1/Mojolicious/Plugin/OpenAPI.pm line 50
	Mojolicious::Plugin::OpenAPI::__ANON__(Pi::Controller::Admin::Questions=HASH(0x3eda788)) called at /usr/local/share/perl/5.22.1/Mojolicious/Renderer.pm line 67
	Mojolicious::Renderer::Helpers::3fc254888e095ff18bc36e1776ca6662::valid_input(Mojolicious::Renderer::Helpers::3fc254888e095ff18bc36e1776ca6662=REF(0x3f1abe0)) called at lib/Pi/Controller/Admin/Questions.pm line 59
	Pi::Controller::Admin::Questions::save_answer(Pi::Controller::Admin::Questions=HASH(0x3eda788)) called at /usr/local/share/perl/5.22.1/Mojolicious.pm line 138
	Mojolicious::__ANON__(undef, Pi::Controller::Admin::Questions=HASH(0x3eda788), CODE(0x3f14ec0), 1) called at /usr/local/share/perl/5.22.1/Mojolicious/Plugins.pm line 15
	Mojolicious::Plugins::__ANON__() called at /usr/local/share/perl/5.22.1/Mojolicious/Plugins.pm line 18
	Mojolicious::Plugins::emit_chain(Mojolicious::Plugins=HASH(0x30e2f78), "around_action", Pi::Controller::Admin::Questions=HASH(0x3eda788), CODE(0x3f14ec0), 1) called at /usr/local/share/perl/5.22.1/Mojolicious/Routes.pm line 87
	Mojolicious::Routes::_action(Mojolicious::Lite=HASH(0x30b8458), Pi::Controller::Admin::Questions=HASH(0x3eda788), CODE(0x3f14ec0), 1) called at /usr/local/share/perl/5.22.1/Mojolicious/Routes.pm line 166
	Mojolicious::Routes::_controller(Mojolicious::Routes=HASH(0x30e2b10), Mojolicious::Controller=HASH(0x3e8c428), HASH(0x3ed9ac8), 1) called at /usr/local/share/perl/5.22.1/Mojolicious/Routes.pm line 36
	Mojolicious::Routes::continue(Mojolicious::Routes=HASH(0x30e2b10), Mojolicious::Controller=HASH(0x3e8c428)) called at /usr/local/share/perl/5.22.1/Mojolicious/Routes.pm line 38
	Mojolicious::Routes::continue(Mojolicious::Routes=HASH(0x30e2b10), Mojolicious::Controller=HASH(0x3e8c428)) called at /usr/local/share/perl/5.22.1/Mojolicious/Routes.pm line 44
	Mojolicious::Routes::dispatch(Mojolicious::Routes=HASH(0x30e2b10), Mojolicious::Controller=HASH(0x3e8c428)) called at /usr/local/share/perl/5.22.1/Mojolicious.pm line 129
	Mojolicious::dispatch(Mojolicious::Lite=HASH(0x30b8458), Mojolicious::Controller=HASH(0x3e8c428)) called at /usr/local/share/perl/5.22.1/Mojolicious.pm line 139
	Mojolicious::__ANON__(undef, Mojolicious::Controller=HASH(0x3e8c428)) called at /usr/local/share/perl/5.22.1/Mojolicious/Plugins.pm line 15
	Mojolicious::Plugins::__ANON__() called at /usr/local/share/perl/5.22.1/Mojolicious.pm line 201
	eval {...} called at /usr/local/share/perl/5.22.1/Mojolicious.pm line 201
	Mojolicious::_exception(CODE(0x3e77768), Mojolicious::Controller=HASH(0x3e8c428)) called at /usr/local/share/perl/5.22.1/Mojolicious/Plugins.pm line 15
	Mojolicious::Plugins::__ANON__() called at /usr/local/share/perl/5.22.1/Mojolicious/Plugins.pm line 18
	Mojolicious::Plugins::emit_chain(Mojolicious::Plugins=HASH(0x30e2f78), "around_dispatch", Mojolicious::Controller=HASH(0x3e8c428)) called at /usr/local/share/perl/5.22.1/Mojolicious.pm line 145
	Mojolicious::handler(Mojolicious::Lite=HASH(0x30b8458), Mojo::Transaction::HTTP=HASH(0x3041220)) called at /usr/local/share/perl/5.22.1/Mojo/Server.pm line 68
	Mojo::Server::__ANON__(Mojo::Server::Daemon=HASH(0x14333d0), Mojo::Transaction::HTTP=HASH(0x3041220)) called at /usr/local/share/perl/5.22.1/Mojo/EventEmitter.pm line 15
	Mojo::EventEmitter::emit(Mojo::Server::Daemon=HASH(0x14333d0), "request", Mojo::Transaction::HTTP=HASH(0x3041220)) called at /usr/local/share/perl/5.22.1/Mojo/Server/Daemon.pm line 103
	Mojo::Server::Daemon::__ANON__(Mojo::Transaction::HTTP=HASH(0x3041220)) called at /usr/local/share/perl/5.22.1/Mojo/EventEmitter.pm line 15
	Mojo::EventEmitter::emit(Mojo::Transaction::HTTP=HASH(0x3041220), "request") called at /usr/local/share/perl/5.22.1/Mojo/Transaction/HTTP.pm line 60
	Mojo::Transaction::HTTP::server_read(Mojo::Transaction::HTTP=HASH(0x3041220), "POST /api/question/answer HTTP/1.1\x{d}\x{a}Connection: upgrade\x{d}\x{a}Host"...) called at /usr/local/share/perl/5.22.1/Mojo/Server/Daemon.pm line 219
	Mojo::Server::Daemon::_read(Mojo::Server::Daemon=HASH(0x14333d0), "e8b245ab2107bbd3d8815a218523c2d4", "POST /api/question/answer HTTP/1.1\x{d}\x{a}Connection: upgrade\x{d}\x{a}Host"...) called at /usr/local/share/perl/5.22.1/Mojo/Server/Daemon.pm line 200
	Mojo::Server::Daemon::__ANON__(Mojo::IOLoop::Stream=HASH(0x3dc59f0)) called at /usr/local/share/perl/5.22.1/Mojo/EventEmitter.pm line 15
	Mojo::EventEmitter::emit(Mojo::IOLoop::Stream=HASH(0x3dc59f0), "read", "POST /api/question/answer HTTP/1.1\x{d}\x{a}Connection: upgrade\x{d}\x{a}Host"...) called at /usr/local/share/perl/5.22.1/Mojo/IOLoop/Stream.pm line 99
	Mojo::IOLoop::Stream::_read(Mojo::IOLoop::Stream=HASH(0x3dc59f0)) called at /usr/local/share/perl/5.22.1/Mojo/IOLoop/Stream.pm line 48
	Mojo::IOLoop::Stream::__ANON__(Mojo::Reactor::Poll=HASH(0x26cf498)) called at /usr/local/share/perl/5.22.1/Mojo/Reactor/Poll.pm line 143
	eval {...} called at /usr/local/share/perl/5.22.1/Mojo/Reactor/Poll.pm line 143
	Mojo::Reactor::Poll::_try(Mojo::Reactor::Poll=HASH(0x26cf498), "I/O watcher", CODE(0x2f9e998), 0) called at /usr/local/share/perl/5.22.1/Mojo/Reactor/Poll.pm line 58
	Mojo::Reactor::Poll::one_tick(Mojo::Reactor::Poll=HASH(0x26cf498)) called at /usr/local/share/perl/5.22.1/Mojo/Reactor/Poll.pm line 99
	Mojo::Reactor::Poll::start(Mojo::Reactor::Poll=HASH(0x26cf498)) called at /usr/local/share/perl/5.22.1/Mojo/IOLoop.pm line 136
	Mojo::IOLoop::start(Mojo::IOLoop=HASH(0x2605140)) called at /usr/local/share/perl/5.22.1/Mojo/Server/Daemon.pm line 39
	Mojo::Server::Daemon::run(Mojo::Server::Daemon=HASH(0x14333d0)) called at /usr/local/share/perl/5.22.1/Mojo/Server/Morbo.pm line 69
	Mojo::Server::Morbo::_spawn(Mojo::Server::Morbo=HASH(0x1433298)) called at /usr/local/share/perl/5.22.1/Mojo/Server/Morbo.pm line 54
	Mojo::Server::Morbo::_manage(Mojo::Server::Morbo=HASH(0x1433298)) called at /usr/local/share/perl/5.22.1/Mojo/Server/Morbo.pm line 34
	Mojo::Server::Morbo::run(Mojo::Server::Morbo=HASH(0x1433298), "myapp.pl") called at /usr/local/bin/morbo line 19

[Sun Nov 19 08:14:26 2017] [debug] 500 Internal Server Error (0.008902s, 112.334/s)

This happened when I installed the latest version of the packages
cpanm Devel::Cycle ojo::Redis2 Mojolicious Minion Mojo::Pg DDP Mojo::mysql PadWalker Mojo::SQLite Mojolicious::Plugin::OpenAPI YAML::Syck List::MoreUtils Mojolicious::Plugin::ShareHelpers

Before the update, there were no such errors.

I need help

**Comment by jhthorsen** [comment]
Hey, I messed up big time with JSON::Validator 1.05. Can you see if it works better with the latest versions?

```
cpanm https://github.com/jhthorsen/json-validator/archive/master.tar.gz
cpanm https://github.com/jhthorsen/mojolicious-plugin-openapi/archive/master.tar.gz
```

These versions should also be available on CPAN soon.

**Comment by sklukin** [comment]
root@0df31fd71f23:/usrc/src/app# perl -MMojolicious::Plugin::OpenAPI -E 'say $Mojolicious::Plugin::OpenAPI::VERSION'
1.22

The same error remained, unfortunately

**Comment by sklukin** [comment]
That helped. There are no more mistakes. Great job!! Thank you!!

**Comment by sklukin** [comment]
I apologize for the delay in checking. A lot of work.
