### ISSUE TITLE
Is it possible to validate all requests to api inside one under function? 

### ISSUE THREAD

**Issue by elcamlost** [jhthorsen/mojolicious-plugin-openapi#51]
I want to validate all requests against openapi inside under sub. (I use Mojo). Earlier, I achieved it like this:
```perl
sub under_openapi {
    ....
     my $spec = $self->match()->endpoint()->pattern()->defaults()->{'openapi.op_spec'};
     $self->stash('openapi.op_spec' => $spec);
     my @errors = $self->openapi()->validate();
    ...
}
```

After this release, I modified (and simplified) it to
```perl
sub under_openapi {
    ....
    my $spec =  $self->openapi()->spec();
    $self->stash('openapi.parameters' => $spec->{'parameters'});
    my @errors = $self->openapi()->validate();
    ...
}
```

So, 
1) why do you read parameters from stash inside **_helper_validate**, and not from $spec itself? Looks like correct data is already there.

2) why not to make validation by default? It can be configured via constructor parameters.

**Comment by jhthorsen** [comment]
1. No, because of inheritance. Have a look at this example spec: https://github.com/jhthorsen/mojolicious-plugin-openapi/blob/master/t/spec.t#L60
2. I don't get what you mean about "It can be configured via constructor parameters". Do you think it's too much boilerplate with `my $c = shift->openapi->valid_input or return;` ?

**Comment by elcamlost** [comment]
Actually, it's matter of habbit. I personally do not like shift at all and more over, prefer perl signatures. Also with validation toggled inside under sub we can disable it all at once, with validation toggled inside each controller we need to change each controller. It's a trivial task (if all developers follow common pattern), but still a bit harder, than comment single line in under sub or set 'validate' key to zero during construction. 

Maybe I can implement it later as a plugin.

**Comment by jhthorsen** [comment]
it should be rather simple now that I've added support for plugins. Even though the feature is not yet documented / officially supported.

Please submit a PR if you like.

https://github.com/jhthorsen/mojolicious-plugin-openapi/blob/master/lib/Mojolicious/Plugin/OpenAPI/Security.pm
