### ISSUE TITLE
How to get full spec

### ISSUE THREAD

**Issue by sklukin** [jhthorsen/mojolicious-plugin-openapi#52]
After update I see dump spec in this view 

```
​​\ {
    parameters    [
        [0] {
            $ref   "#/parameters/event_id"
        } (tied to JSON::Validator::Ref)
    ],
    responses     {
        200       {
            description   "Get event",
            schema        {
                $ref   "#/definitions/event_result"
            } (tied to JSON::Validator::Ref)
        },
        202       {
            description   "Error",
            schema        {
                $ref   "#/definitions/error"
            } (tied to JSON::Validator::Ref)
        },
        default   {
            description   "Default response.",
            schema        {
                properties   {
                    errors   {
                        items   {
                            properties   {
                                message   {
                                    type   "string"
                                },
                                path      {
                                    type   "string"
                                }
                            },
                            required     [
                                [0] "message"
                            ],
                            type         "object"
                        },
                        type    "array"
                    }
                },
                required     [
                    [0] "errors"
                ],
                type         "object"
            }
        }
    },
    x-mojo-name   "get_event",
    x-mojo-to     "Admin::Events#get_event"
}
```

How to get full spec with structs under ref?

**Comment by sklukin** [comment]
https://github.com/jhthorsen/json-validator/blob/master/lib/JSON/Validator/Ref.pm
Tie for use with cyclical references? Now I can use cyclical references?

**Comment by jhthorsen** [comment]
I don’t get what “dump spec” means. I don’t understand this issue at all :(

* What are you doing?
* What is the expected outcome?
* What is the outcome you’re observing?

**Comment by sklukin** [comment]
I get the data out from `$ref "#/definitions/event_result"`  which in the end contains a list of fields and pass them to frontend app. 

Before the upgrade to the latest version it worked.

**Comment by sklukin** [comment]
Update

**Comment by jhthorsen** [comment]
What has changed?

**Comment by sklukin** [comment]
Hi!
Befor update I can get list from that path
my $key   = '/responses/200/schema/properties/result/properties/event_item/properties';
After update I cant. 
Error - Can't use an undefined value as a HASH reference
I think its because of 

> tied to JSON::Validator::Ref

Before that in this was not ref.

If this is a stupid question, then I'll forgive

**Comment by jhthorsen** [comment]
The way you do this now is:

```
$jv->get([qw(paths  /whatever get responses 200 schema properties result properties event_item properties]);
```

https://metacpan.org/pod/JSON::Validator#get

I'm not going to revert the change where I keep the $ref as-is.

**Comment by jhthorsen** [comment]
Not sure where this stands now, but closing the issue based on inactivity.

Please ask in #swagger on irc.perl.org if you have further questions.
