### ISSUE TITLE
Serving of the OpenAPI spec ought not to be transformed version

### ISSUE THREAD

**Issue by mohawk2** [jhthorsen/mojolicious-plugin-openapi#58]
Further to discussion on `#swagger`. When I have a Mojolicious app that has a `Mojolicious::Plugin::OpenAPI` endpoint starting at `/api` that has a `$ref`, and I request `/api`, the `$ref` is:

Got: `#/definitions/_api_data_yml-definitions/Whatever`

Expected: `#/definitions/Whatever`

The reason to care about this is that my code reads the actual `$ref` to determine the return "type" of the request. This works great when using `JSON::Validator::OpenAPI` to read a spec directly off a disk, but not when read from an endpoint as mentioned above.

I understand that there is a concern about "leaking" `x-mojo-*` information in the spec, and would not be affected if just that were filtered out by default. I also understand there is a use-case for the bundling being still available, and I would also not be affected if that were available with e.g. a `?bundle=1` CGI arg on the spec. However, currently the specs being served I cannot use.

**Comment by mohawk2** [comment]
By the way, this would also work fine if the `$ref` were still the same text. It's the different name that's causing the problem.

**Comment by le-garff-yoann** [comment]
I have the exact same issue. Could not use `OpenAPI::Client` because of this.

**Comment by jhthorsen** [comment]
@le-garff-yoann: How did it break OpenAPI::Client?

**Comment by jhthorsen** [comment]
I think I like the change in https://github.com/jhthorsen/json-validator/pull/94, but I'm not sure if I like serving the "unbundled" version by default. Consider this scenario:

1. You load `file:///$app_root/spec.json`
2. That file has a `$ref` pointing to `other.json`
3. You serve the unbundled version of `spec.json` and everything fails, since there's no way for a client/parser/... to fetch `other.json`.

**Comment by mohawk2** [comment]
That's a good point. My use-case problem is solved with the JV#94 PR, and I'm not in favour of creating more complication!

**Comment by jhthorsen** [comment]
I'm closing this then. Let me know if this issue should be re-opened @le-garff-yoann.

**Comment by le-garff-yoann** [comment]
Sorry, wasn't here... i don't know if you should re-open **this** issue ^^

But my case/problem is the next:
* Server side, i load my spec file like this:
1. 
```perl
$self->helper('clovershell.openapi.url' => sub { state $p = shift->app->home->child('share', 'clovershell.json') });
```
N.B: I believe `shift->app->home->child` doesn't returns a full path. 
2.
```perl
    $self->plugin(OpenAPI => {
        url => $self->clovershell->openapi->url
    });
```
* When i `curl` my API, i now (since the PR has been merged) get `$ref` like this one: `$ref":"#\/definitions\/__devel_clovershell_clovershell-server_share_clovershell_json-_definitions_error`
* When i use `OpenAPI::Client` via the URL that serve the API, i get this kind of error:

```
  Invalid JSON specification HASH(0x31dc6e8):
  - /definitions/__devel_clovershell_clovershell-server_share_clovershell_json-_parameters_cloverName: Properties not allowed: in, name.
  - /definitions/__devel_clovershell_clovershell-server_share_clovershell_json-_parameters_tagName: Properties not allowed: in, name.
  - /definitions/__devel_clovershell_clovershell-server_share_clovershell_json-_parameters_tagNameInQuery: Properties not allowed: in, name.
  - /definitions/__devel_clovershell_clovershell-server_share_clovershell_json-_parameters_userinfo: Properties not allowed: in, name, schema.
  - /definitions/__devel_clovershell_clovershell-server_share_clovershell_json-_responses_error: Properties not allowed: schema. at /root/perl5/perlbrew/perls/perl-5.26.1/lib/site_perl/5.26.1/JSON/Validator.pm line 144.
        JSON::Validator::load_and_validate_schema(JSON::Validator::OpenAPI::Mojolicious=HASH(0x35ddd30), Mojo::URL=HASH(0x35c0ce8), HASH(0x35c05e0)) called at /root/perl5/perlbrew/perls/perl-5.26.1/lib/site_perl/5.26.1/JSON/Validator/OpenAPI.pm line 20
        JSON::Validator::OpenAPI::load_and_validate_schema(JSON::Validator::OpenAPI::Mojolicious=HASH(0x35ddd30), Mojo::URL=HASH(0x35c0ce8), HASH(0x35c05e0)) called at /root/perl5/perlbrew/perls/perl-5.26.1/lib/site_perl/5.26.1/OpenAPI/Client.pm line 67
        OpenAPI::Client::new("OpenAPI::Client", Mojo::URL=HASH(0x35c0ce8)) called at /root/perl5/perlbrew/perls/perl-5.26.1/lib/site_perl/5.26.1/Clovershell/Base/CLI/Command.pm line 59
        eval {...} called at /root/perl5/perlbrew/perls/perl-5.26.1/lib/site_perl/5.26.1/Clovershell/Base/CLI/Command.pm line 54
        Clovershell::Base::CLI::Command::execute(Clovershell::CLI::Command::find=HASH(0x3325cf8), Getopt::Long::Descriptive::Opts::__OPT__::2=HASH(0x34cfdf0), ARRAY(0x29f5270), CODE(0x31bfd40)) called at /root/perl5/perlbrew/perls/perl-5.26.1/lib/site_perl/5.26.1/Clovershell/CLI/Command/find.pm line 144
        Clovershell::CLI::Command::find::execute(Clovershell::CLI::Command::find=HASH(0x3325cf8), Getopt::Long::Descriptive::Opts::__OPT__::2=HASH(0x34cfdf0), ARRAY(0x29f5270)) called at /root/perl5/perlbrew/perls/perl-5.26.1/lib/site_perl/5.26.1/App/Cmd.pm line 468
        App::Cmd::execute_command(Clovershell::CLI=HASH(0x26219d0), Clovershell::CLI::Command::find=HASH(0x3325cf8), Getopt::Long::Descriptive::Opts::__OPT__::2=HASH(0x34cfdf0)) called at /root/perl5/perlbrew/perls/perl-5.26.1/lib/site_perl/5.26.1/App/Cmd.pm line 321
        App::Cmd::run("Clovershell::CLI") called at /root/perl5/perlbrew/perls/perl-5.26.1/bin/clovershell line 11
```

**Comment by jhthorsen** [comment]
Seems like you have an invalid spec. But it's impossible for me to know what is wrong with it, since you're not sharing that part. Please join #swagger on irc.perl.org and share the spec somewhere for me/us to investigate.

**Comment by le-garff-yoann** [comment]
Ok i will join the IRC. But it's weird because the server part work (it doesn't crash with an exception).

**Comment by jhthorsen** [comment]
It's the same validator, so there must be something weird going on with the version of JSON::Validator that is loaded. At least I can't come up with any other reason.

**Comment by le-garff-yoann** [comment]
It run well if i use i load the spec from disk with `OpenAPI::Client`.

**Comment by mohawk2** [comment]
@le-garff-yoann I believe JV 2.01 should mean you don't see these refs being munged anymore. Could you add that to your `cpanfile`, which doesn't currently constrain JV at all, deploy, and try again?

**Comment by le-garff-yoann** [comment]
@mohawk2 I already use JV 2.01.

I have the same problem with this app: https://github.com/le-garff-yoann/t-app
Could someone test it?

**Comment by mohawk2** [comment]
If you add tests that fail, and include an invocation line in `README.md`, showing immediately what's going wrong, one of us can take a look at why.

**Comment by le-garff-yoann** [comment]
@mohawk2 
I just completed the README. ;)

**Comment by jhthorsen** [comment]
Please ask on irc. This is not a support channel.
