### ISSUE TITLE
CORS support for OpenAPI

### ISSUE THREAD

**Issue by kivilahtio** [jhthorsen/mojolicious-plugin-openapi#6]
We need CORS support for our API.
We have a implementation for the Swagger2
https://github.com/KohaSuomi/swagger2/blob/cors/lib/Mojolicious/Plugin/Swagger2/CORS.pm

Maybe something like this will eventually find it's way to Mojolicious::Plugin::OpenAPI::CORS

A goodread for understanding CORS more deply: "CORS in action"

**Comment by jhthorsen** [comment]
What about https://developer.mozilla.org/en-US/docs/Web/HTTP/Access_control_CORS ?

**Comment by jhthorsen** [comment]
I'm closing this, but leaving #14 open.
