### ISSUE TITLE
Any plan for openapi 3 support?

### ISSUE THREAD

**Issue by deathiop** [jhthorsen/mojolicious-plugin-openapi#65]
Do you have plans to support the 3.0 specification?

**Comment by jberger** [comment]
This is waiting on final decisions from OpenAPI itself. We've already had one issue opened (https://github.com/jhthorsen/mojolicious-plugin-openapi/issues/20) and there is one on the upstream Perl module too (https://github.com/jhthorsen/json-validator/issues/41)

**Comment by jberger** [comment]
Here is the issue on OpenAPI itself: https://github.com/OAI/OpenAPI-Specification/issues/1032
