### ISSUE TITLE
Unexpected error message when response code is not allowed

### ISSUE THREAD

**Issue by glauschwuffel** [jhthorsen/mojolicious-plugin-openapi#66]
Hi,

with version 1.25 of this plugin I notice an unexpected behaviour.

When my application is responding with a response code that is not specified in the API specification, I get the following error message:
````
[warn] OpenAPI >>> POST <ROUTE> [{"message":"Expected object - got null.","path":"\/"}]
````

I'd expect a specific error message telling me that the response code is not specified in the API specification (or something like that).

**Comment by jhthorsen** [comment]
Me too... I’ll hopefullt have some time to look at it next week.

**Comment by glauschwuffel** [comment]
If you point me in the right direction I might be able to fix it. Is there anything I can do to help you?

**Comment by jhthorsen** [comment]
I don't understand how this is possible though. Have you disabled the `default_response` ?

**Comment by jhthorsen** [comment]
I think what is going on is that you render undef or something, and that is not compatible with the default response. I can't say for sure because of lack of code/example, but I'm pretty sure that is it.

Look for "default_response" here: https://metacpan.org/pod/Mojolicious::Plugin::OpenAPI#register

**Comment by glauschwuffel** [comment]
Thanks for the hint. I am indeed trying to render undef since the body is empty. What would be the correct way?

**Comment by jhthorsen** [comment]
If you want to render an empty response..? Check out this test for empty response: https://github.com/jhthorsen/mojolicious-plugin-openapi/blob/5a0f0a2538b79e752f6d8db2b4ed55b7c0aedf31/t/empty-string.t

**Comment by glauschwuffel** [comment]
Thanks, I’ll take a look at it!
