### ISSUE TITLE
Export checks from validation object into formats for JSON::Validator

### ISSUE THREAD

**Issue by KES777** [jhthorsen/mojolicious-plugin-openapi#68]
It would cool if you automatically export [checks](http://mojolicious.org/perldoc/Mojolicious/Validator#checks) from validator object into [formats](https://metacpan.org/pod/JSON::Validator#formats) for JSON::Validator

So this will allow to just define format in my scheme:

    type: string
    format: is_network

Which is similar to:

    $v->optional("name")->is_network

**Comment by jhthorsen** [comment]
This cannot be done now, because the API is not the same. It could be cool to do it in the future though.

**Comment by jhthorsen** [comment]
If you're still interested, then please re-open an issue for JV: https://github.com/jhthorsen/json-validator/issues
