### ISSUE TITLE
Document `reply.openapi` in main module

### ISSUE THREAD

**Issue by polettix** [jhthorsen/mojolicious-plugin-openapi#7]
Hi! First of all thanks for this great module, I discovered Swagger just when I was starting designing a simple API and... *presto!*, there Is a module for Mojolicious in CPAN.

The [tutorial](https://metacpan.org/pod/distribution/Mojolicious-Plugin-OpenAPI/lib/Mojolicious/Plugin/OpenAPI/Guides/Tutorial.pod) talks about `reply.openapi` a couple of times (e.g. [here](https://metacpan.org/pod/distribution/Mojolicious-Plugin-OpenAPI/lib/Mojolicious/Plugin/OpenAPI/Guides/Tutorial.pod#Specification) and [here](https://metacpan.org/pod/distribution/Mojolicious-Plugin-OpenAPI/lib/Mojolicious/Plugin/OpenAPI/Guides/Tutorial.pod#Controller)), [pointing](https://metacpan.org/pod/Mojolicious::Plugin::OpenAPI#reply.openapi) to non-existing documentation in the main module.

I was also curious why `reply.openapi` instead of `openapi.reply`, like the input validation stuff.

**Comment by jhthorsen** [comment]
Thank you for the kind words 😄 

The "reply.openapi" helper is not documented in the main module, since I want people to use `render(openapi => ...)` instead, like shown in the SYNOPSIS.

The reason why it was originally called "reply.openapi" instead of "openapi.reply", is because of the rest of the Mojolicious reply helpers are called "reply.not_found", "reply.exception", "reply.static", ...

I'm working on removing "reply.openapi" from the tutorial now.

Thanks for reporting this bug!

**Comment by jhthorsen** [comment]
What do you think about the documentation changes in 4406a27?

@jberger and @mrenvoize: Do you have any input on the wording?

**Comment by polettix** [comment]
Seems much clearer now. It would probably be good to understand better how one is supposed to write the validator for output, e.g. with a pointer to some specific place in the specification (I wasn't able to find one quickly) or possibly to your other validation module.

**Comment by jhthorsen** [comment]
The swagger/OpenAPI spec is used to validate the output. It's done automatically... not sure if I understood the question. Please elaborate on what is unclear.

**Comment by polettix** [comment]
Nothing unclear actually, sorry I gave you this impression.

I now understand that probably the best path for me is to start with the Swagger Editor and then use the outcome with this module, not the other way around.

**Comment by jhthorsen** [comment]
Yes, you need a specification for this plugin to work.

**Comment by polettix** [comment]
I initially started editing the specification based on the examples, but I quickly hit the wall of ignorance. I'm now working on the Swagger Editor to set it up, then I'll move to the plugin. Thanks!

**Comment by jhthorsen** [comment]
You can join the #swagger channel on irc.perl.org and ask us for help if you like.
