### ISSUE TITLE
Ambigious error message

### ISSUE THREAD

**Issue by KES777** [jhthorsen/mojolicious-plugin-openapi#71]
> "Using default_handler to render data since 'openapi' was not found in stash. Set 'handler' in stash to avoid this message."

Do you mean set 'openapi' in stash?

**Comment by jhthorsen** [comment]
No, I mean handler. The thing is that "handler" variable is set to "openapi", but when that renderer is called, it does not find any "openapi" key set in the stash which makes it confused.

**Comment by KES777** [comment]
in any case falling back to default 'html' for request to API is not good idea (except for development)

**Comment by jhthorsen** [comment]
This is not an issue in the plugin, it's an issue in your code. I cannot guess what you want to render, unless you tell your application that.
