### ISSUE TITLE
Can not disable coerce for all

### ISSUE THREAD

**Issue by KES777** [jhthorsen/mojolicious-plugin-openapi#72]
>Odd number of elements in anonymous hash at /home/kes/work/projects/tucha/monkeyman/app/tucha/../..//local/lib/perl5/JSON/Validator.pm line 119

	$app->plugin(OpenAPI => {
		coerce => 0,
	});

**Comment by jhthorsen** [comment]
Where is it documented that you can pass on `0` ?

Try with an empty hash instead.

**Comment by KES777** [comment]
>WARNING! Enabling coercion might hide bugs in your api, which would have been detected if you were strict.

>Where is it documented that you can pass on 0 ? 
I suppose if there is the operation there should be reverse operation, is not?

**Comment by jhthorsen** [comment]
Oh, right. I just removed the warning in f7bf50a02946db00aa52337e58b618ed6b033433 and documentation for `coerce(1)` in 41ad1a64d10340047ed7c6815eaa32e7c839fc63

Thanks!

**Comment by KES777** [comment]
mm. Is it hide bugs or not? If "yes", I will prefer to see warning

**Comment by jhthorsen** [comment]
I have not experienced any issues. That's why I feel it's safe to remove the warning now.
