### ISSUE TITLE
OpenAPI v3

### ISSUE THREAD

**Issue by TBSliver** [jhthorsen/mojolicious-plugin-openapi#75]
Cant tell if this supports OpenAPI v3? if not at present, is that planned for the future at all?

**Comment by jberger** [comment]
Sadly, can't do anything until they provide a spec.  https://github.com/jhthorsen/mojolicious-plugin-openapi/issues/65

**Comment by jhthorsen** [comment]
Just merged https://github.com/jhthorsen/json-validator/pull/124 which has highly EXPERIMENTAL support for v3. Please submit issues and/or PRs for things that is not working.
