### ISSUE TITLE
Add support for checking Content-Type before validating the input

### ISSUE THREAD

**Issue by jpsalvesen** [jhthorsen/mojolicious-plugin-openapi#76]
If the JSON itself is invalid, the code inside the controller gets invoked (and gets an undef when you call app->req->json etc. 

Basically, you can't trust the incoming data to be there as defined by your definitions...

**Comment by jhthorsen** [comment]
Can you make a failing test for this?

**Comment by jhthorsen** [comment]
So the test above shows that everything works as expected if you add `"required":true`.

**Comment by jhthorsen** [comment]
Checks for consumes and produces are implemented in JSON::Valdiator 4.xx.
