### ISSUE TITLE
delay helper is DEPRECATED (Mojolicious::Controller)

### ISSUE THREAD

**Issue by rage311** [jhthorsen/mojolicious-plugin-openapi#77]
It looks like as of Mojolicious 7.78, the `delay` helper is deprecated.  It's being used in Security.pm: https://github.com/jhthorsen/mojolicious-plugin-openapi/blob/3316aab0b358b39c2d7e579a9673e876dc950a08/lib/Mojolicious/Plugin/OpenAPI/Security.pm#L28

Here's the message showing up in the running app:

`delay helper is DEPRECATED at /home/me/perl5/perlbrew/perls/perl-5.26.2/lib/site_perl/5.26.2/Mojolicious/Controller.pm line 32.`

References:

https://github.com/kraih/mojo/blob/b2088054d4db9d72409cb365dda6d6bacbd015e1/lib/Mojolicious/Plugin/DefaultHelpers.pm#L35

https://github.com/kraih/mojo/blob/b2088054d4db9d72409cb365dda6d6bacbd015e1/Changes#L41

**Comment by jhthorsen** [comment]
Thanks for reporting in! 👍

**Comment by rage311** [comment]
Awesome.  Thanks for the plugin itself and the quick fix.  It's been very useful for me.

**Comment by jhthorsen** [comment]
Thanks! Happy to hear :)
