### ISSUE TITLE
Why does M::P::OpenAPI dump your spec file by default?

### ISSUE THREAD

**Issue by jamesbriggs** [jhthorsen/mojolicious-plugin-openapi#83]
The default should be off on dumping the spec file on /.

**Comment by jhthorsen** [comment]
Why not?

The reason is that OpenAPI clients need the spec to be able to communicate with your server.

**Comment by jhthorsen** [comment]
Maybe you misunderstand: An OpenAPI client is a library and not a person. One example is https://metacpan.org/pod/OpenAPI::Client

Without the spec file, there’s no way for the client to work.

You also didn’t answer my question, so I don’t know why the spec should _not_ be served.

**Comment by jhthorsen** [comment]
Closing this issue based on lack of feedback.
