### ISSUE TITLE
Would it make sense to allow multiple specs?

### ISSUE THREAD

**Issue by srchulo** [jhthorsen/mojolicious-plugin-openapi#84]
Feel free to close this if you don't think this makes sense. 

I have a use case where I have a public API and an app API. I don't want the app API to be exposed with the public one, so I generate the clients separately. However, I have to keep one file with all of the api calls so that Mojolicious::Plugin::OpenAPI can route to all of my methods. It would be nice if spec could support an arrayref, so you could have a public.yaml and an app.yaml, for example.

**Comment by jhthorsen** [comment]
I don't think it makes sense to have one public API and an app API. Can you give me more details for why you need this?

Are you thinking about that you don't want the JSON to be exposed on `/basePath.json` route? If that is the case, then you should be able to change the endpoint of that route to disable the rendering. Something like this:

```
$app->routes->lookup("some_api_name")->to(cb => sub { shift->render(status => 403) });
```

**Comment by srchulo** [comment]
The reason I wanted this was so that people who can't login to the site aren't aware of the API calls to affect accounts (anyone can't sign up for this site, they need to be approved), and also for code size. My public API for the public site only needs the login API call, so it's also nice that I don't need to download the whole API for users who are just viewing the public site, especially since my app API is pretty large.

**Comment by jhthorsen** [comment]
I think you should rather split the API into two parts, like this:

```
$app->plugin(OpenAPI => {url => $app->home->rel_file("private-api.json")});
$app->plugin(OpenAPI => {url => $app->home->rel_file("public-api.json")});
```

Each spec need to have it's own `basePath`.

**Comment by jhthorsen** [comment]
No.

You can load the OpenAPI plugin as many times as you like, but the different specifications must have different `basePath`.

**Comment by srchulo** [comment]
Ah, I see. Well that sounds like the proper way to handle this. Thanks!
