### ISSUE TITLE
Please do not repalce host name from spec with "Host" from request

### ISSUE THREAD

**Issue by vtmas** [jhthorsen/mojolicious-plugin-openapi#86]
Hello jhtorsen,

First of all thank you for the amazing job you have done with OpenAPI.

This is regarding the host in the spec being replaced by the "Host" header in the request.
I am using mojo with hypnotoad behind an nginx as a reverse proxy. (https://mojolicious.org/perldoc/Mojolicious/Guides/Cookbook#Nginx)

In this setup the rendered spec has the host repalced with "127.0.0.1". This way unfortunately the "Try out" function of the Swagger UI is incompatible (as it tries to query the localhost the browser is ran on) :(

Is this something you could fix this?
https://github.com/jhthorsen/mojolicious-plugin-openapi/blob/c7f5608a5aec0a318668070e89ca7f5a54d268fd/lib/Mojolicious/Plugin/OpenAPI.pm#L247
Just adding the host from the spec?

Thank you very much,
Tamás

**Comment by jhthorsen** [comment]
I think you're missing out on something in your nginx setup. Have you set all the headers in the cookbook below and set `MOJO_REVERSE_PROXY`?

* https://mojolicious.org/perldoc/Mojolicious/Guides/Cookbook#Nginx
* https://mojolicious.org/perldoc/Mojo/Server/Hypnotoad#proxy
* https://mojolicious.org/perldoc/Mojo/Server#reverse_proxy

**Comment by vtmas** [comment]
this is such a facepalm moment. I indeed messed up the Nginx config. 
Setting     proxy_set_header Host $host; solved it.

Sorry for bothering you. And thank you for the answer :)

**Comment by jhthorsen** [comment]
I’m just glad I didn’t have to change my code 😉
