### ISSUE TITLE
Tutorial refers to invalid error.json url

### ISSUE THREAD

**Issue by sjn** [jhthorsen/mojolicious-plugin-openapi#89]
References to http://git.io/vcKD4 found both in mojolicious-plugin-openapi and json-validator should probably be updated, as that url now gives a 404. I grepped for vcKD4 and found a few.

Maybe use https://git.io/fAF2t instead in releases where this error document is correct, and possibly add another one if you're going for the error.json change you mentioned in #88 ?

**Comment by jhthorsen** [comment]
This is not entirely true, since that URL is bundled in JSON::Validator.

https://github.com/jhthorsen/json-validator/blob/master/lib/JSON/Validator/cache/630949337805585c8e52deea27d11419

**Comment by sjn** [comment]
Yep, it's there, but that's not obvious from a newbie's perspective. This is "magical behavior" that "somehow just works". I'd say this may be a source of confusion. :smiley:

**Comment by jhthorsen** [comment]
Ok! Thanks for the feedback. Please review the commit above, and let me know what you think.
