### ISSUE TITLE
Output validation doesn't distinguish between undef and empty string

### ISSUE THREAD

**Issue by plk** [jhthorsen/mojolicious-plugin-openapi#9]
I have an operation which returns just a "string" type. If the string is empty (but defined), it throws a 501 at output validation. Non-empty strings are fine. Empty arrays and objects are fine but empty strings seemingly not? This is with 1.03.

**Comment by jhthorsen** [comment]
Can you provide an example schema? Also, if possible, could you try to write a failing test? You can get inspiration from tests like...

* https://github.com/jhthorsen/mojolicious-plugin-openapi/blob/master/t/reply-asset.t
* https://github.com/jhthorsen/mojolicious-plugin-openapi/blob/master/t/synopsis.t

**Comment by plk** [comment]
Here is a sample - the empty string return gives an output validation 501 error but a non-empty string doesn't. I am not sure this is correct as it's different from empty arrays or objects which don't fail validation - an empty string is still a string and should be allowed as a return value.

```
use Mojo::Base -strict;
use Test::Mojo;
use Test::More;
use Mojolicious::Lite;

get '/string' => sub {
  my $c = shift->openapi->valid_input or return;
  # $c->reply->openapi(200 => 'a');
  $c->reply->openapi(200 => '');
  },
  'File';

plugin OpenAPI => {url => 'data://main/file.json'};

my $t = Test::Mojo->new;

$t->get_ok('/api/string')->status_is(200);

done_testing;

package main;
__DATA__
@@ file.json
{
  "swagger" : "2.0",
  "info" : { "version": "0.8", "title" : "Test binary data" },
  "schemes" : [ "http" ],
  "basePath" : "/api",
  "paths" : {
    "/string" : {
      "get" : {
        "operationId" : "File",
        "responses" : {
          "200": {
            "description": "response",
            "schema": { "type": "string" }
          }
        }
      }
    }
  }
}
```

**Comment by jhthorsen** [comment]
Thank you! 👍
