### ISSUE TITLE
OpenAPI plugin breaks other plugins if change app->renderer->default_handler

### ISSUE THREAD

**Issue by elcamlost** [jhthorsen/mojolicious-plugin-openapi#91]
We have a [lite app](https://gist.github.com/elcamlost/0004fbea6276c06d94f007078009b87e)
Changing default_handler from ep to something else leads to unexpected behaviour - Minion::Admin plugin stops to work correctly.

The reason of this behavior lies [here](https://github.com/jhthorsen/mojolicious-plugin-openapi/blob/master/lib/Mojolicious/Plugin/OpenAPI.pm#L148-L149).

Mojolicious::Controller should not pass handler option to Mojolicious::Renderer if we want to use handler auto-detection feature. OpenAPI plugin always alter handler option to default for non openapi routes and it breaks handler detection.

**Comment by elcamlost** [comment]
https://github.com/elcamlost/mojolicious-plugin-openapi/commit/eb95742b8785b1130f15f437784bbcc816e929ec

Looks like this change fixes it.

But I'm pretty sure, that it's not good idea delete something from stash like these.

**Comment by jhthorsen** [comment]
This will be fixed by #93.
