### ISSUE TITLE
Manual route wiring using app->routes->find($operationId)->to(...) doesnt work since 2.0

### ISSUE THREAD

**Issue by egormakarov** [jhthorsen/mojolicious-plugin-openapi#92]
In 1.30 I let the OpenAPI-Plugin to create all routes from the spec and then wire them to controllers in `startup` (with `routes->find($operationId)->to(...)`). In 2.0 I now get an error `[OpenAPI] Could not find route by name ...`.

I am not sure if the change in behavior was intentional. I believe the cange came with the fix for #87.
In case it is, can you possibly make the old behavior configurable?

Here is an example.

What is expected: application serves pets
What happens: application exits during startup with the error "[OpenAPI] Could not find route by name 'getPets'."

```perl
#!/usr/bin/env perl

package App::Controller::Pets;
use Mojo::Base 'Mojolicious::Controller';

sub get_pets {
  my ($self) = @_;
  $self->render(openapi => [
    { id => 1, name => 'Nif-Nif' },
    { id => 2, name => 'Naf-Naf' },
    { id => 3, name => 'Nuf-Nuf' },
  ]);
}

package App;
use Mojo::Base 'Mojolicious';

sub startup {
  my ( $self ) = @_;
  $self->plugin(OpenAPI => { url => 'data://main/pets.yaml' });
  # wire to implementation (since 2.0 this dies with
  # "[OpenAPI] Could not find route by name 'getPets'.")
  $self->routes->find('getPets')->to('pets#get_pets');
}

package main;
use strict;
use warnings;
use Mojolicious::Commands;
Mojolicious::Commands->start_app('App');

1;

__DATA__
@@ pets.yaml
swagger: '2.0'
info:
  version: 1.0.0
  title: Swagger Petstore
  description: >-
    A sample API that uses a petstore as an example to demonstrate features in
    the swagger-2.0 specification
  termsOfService: 'http://swagger.io/terms/'
  contact:
    name: Swagger API Team
  license:
    name: MIT
host: petstore.swagger.io
basePath: /api
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /pets:
    get:
      description: Returns all pets from the system that the user has access to
      operationId: getPets
      produces:
        - application/json
      responses:
        '200':
          description: A list of pets.
          schema:
            type: array
            items:
              $ref: '#/definitions/Pet'
definitions:
  Pet:
    type: object
    required:
      - id
      - name
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
      tag:
        type: string
```

**Comment by jhthorsen** [comment]
Why don't you just use `x-mojo-to` directly in your spec instead?

**Comment by jhthorsen** [comment]
Scroll down to `x-mojo-to` in the tutorial for more information: https://metacpan.org/pod/distribution/Mojolicious-Plugin-OpenAPI/lib/Mojolicious/Plugin/OpenAPI/Guides/Tutorial.pod#Specification

**Comment by egormakarov** [comment]
Ok, thank you. The only small problem remains that I always need to provide that implementation detail (`x-mojo-to`) as part of the (potentially public) API contract. Is there any options to filter those (`x-mojo-*`) out while serving the spec to outside world?

**Comment by egormakarov** [comment]
slightly related: does this line make sense? `! $r && $op_spec->{operationId}` cant be reached at this point https://metacpan.org/source/JHTHORSEN/Mojolicious-Plugin-OpenAPI-2.00/lib/Mojolicious/Plugin/OpenAPI.pm#L110

**Comment by jhthorsen** [comment]
I don't understand why people (You're not alone) want to hide "x-mojo-to" from the public API.

What do you mean about "cant be reached at this point"?

**Comment by jhthorsen** [comment]
Closing this based on inactivity.

**Comment by XSven** [comment]
> I don't understand why people (You're not alone) want to hide "x-mojo-to" from the public API.

because a REST clients that consume the OpenAPI specification shouldn't be bothered with extra functionality that is not covered by the standard OpenAPI specification.

PS: The above approach that is based on the standard `operationId` seems to work again. Both `find()` and `lookup()` work. The approach should be documented at an appropriated place because it helps to avoid `x-mojo-*` attributes.

**Comment by XSven** [comment]
I have found again the experimental [op_spec_to_route](https://metacpan.org/pod/Mojolicious::Plugin::OpenAPI#op_spec_to_route) OpenAPI configuration option. Unfortunately it is a callback that presumably cannot be added to a `NotYAMLConfig` config file?!

**Comment by jberger** [comment]
You would need to apply that to the loaded config after loading it. If you only have one callback to apply, that's easy, just hard-code it. If not then define the code blocks in your application and select them by name from your config. That's basically how the job definitions for Minion work.
