### ISSUE TITLE
Use of uninitialized value in length warning when using referring to URL

### ISSUE THREAD

**Issue by jlcooper** [jhthorsen/mojolicious-plugin-openapi#96]
When I use `$ref` to reference another schema by URL I get the following warning
```
Use of uninitialized value in length at cpan/lib/perl5/Mojo/IOLoop/Stream.pm line 37.
```

I've put together the an example script that shows the warning in action - 
[exampleScript.txt](https://github.com/jhthorsen/mojolicious-plugin-openapi/files/2604959/exampleScript.txt)

**Comment by jhthorsen** [comment]
Which version of perl do you have?

**Comment by jlcooper** [comment]
And sure enough the warning goes away with a newer version of Perl - Thanks.
